import { GitHubRepository, GitHubLanguages, GitHubContributor, RepositoryAnalysis } from "@/types/github";
import { CodeHealthResult } from "@/types/codeHealth";
import { formatNumber } from "@/utils/formatNumber";
import { formatSize } from "@/utils/formatSize";

export interface GenerateMarkdownReportOptions {
  repository: GitHubRepository;
  languages?: GitHubLanguages;
  contributors?: GitHubContributor[];
  readme?: string;
  analysis?: RepositoryAnalysis | null;
  aiSummary?: string;
  aiLoading?: boolean;
  codeHealth?: CodeHealthResult | null;
  codeHealthLoading?: boolean;
  codeHealthError?: string | null;
}

export function generateMarkdownReport({
  repository,
  languages = {},
  contributors = [],
  analysis,
  aiSummary,
  aiLoading,
  codeHealth,
  codeHealthLoading,
  codeHealthError,
}: GenerateMarkdownReportOptions): string {
  const lines: string[] = [];

  // Title & Header
  lines.push(`# Repository Analysis Report: ${repository.full_name}`);
  lines.push(`> Generated by CodeOrbit GitHub-Analyzer on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}\n`);

  // 1. Overview & General Info
  lines.push(`## 📊 Overview`);
  lines.push(`- **Repository:** [${repository.full_name}](${repository.html_url})`);
  lines.push(`- **Owner:** ${repository.full_name.split("/")[0] || "N/A"}`);
  lines.push(`- **Description:** ${repository.description ? repository.description.trim() : "No description provided."}`);
  lines.push(`- **Primary Language:** ${repository.language || "Not specified"}`);
  lines.push(`- **License:** ${repository.license?.name || "No License"}`);
  lines.push(`- **Default Branch:** \`${repository.default_branch || "main"}\``);
  lines.push(`- **Repository Size:** ${formatSize(repository.size)}`);
  lines.push("");

  // 2. Metrics Summary Table
  lines.push(`## 📈 Key Metrics`);
  lines.push(`| Metric | Value |`);
  lines.push(`| :--- | :--- |`);
  lines.push(`| **Stars** | ⭐ ${formatNumber(repository.stargazers_count)} (${repository.stargazers_count.toLocaleString()}) |`);
  lines.push(`| **Forks** | 🍴 ${formatNumber(repository.forks_count)} (${repository.forks_count.toLocaleString()}) |`);
  lines.push(`| **Open Issues** | 🐛 ${formatNumber(repository.open_issues_count)} (${repository.open_issues_count.toLocaleString()}) |`);
  if (analysis) {
    lines.push(`| **Repository Health Score** | 🛡️ ${analysis.score} / 100 |`);
  }
  lines.push("");

  // 3. Repository Signals (Analysis)
  if (analysis) {
    lines.push(`## 🛡️ Repository Signals`);
    lines.push(`| Signal | Status |`);
    lines.push(`| :--- | :--- |`);
    lines.push(`| **Documentation** | ${analysis.documentation} |`);
    lines.push(`| **Maintenance** | ${analysis.maintenance} |`);
    lines.push(`| **Popularity** | ${analysis.popularity} |`);
    lines.push(`| **Activity** | ${analysis.activity} |`);
    lines.push(`| **Community** | ${analysis.community} |`);
    lines.push("");
  }

  // 4. Languages Breakdown
  const languageEntries = Object.entries(languages);
  lines.push(`## 💻 Language Breakdown`);
  if (languageEntries.length > 0) {
    const totalBytes = languageEntries.reduce((sum, [, bytes]) => sum + bytes, 0);
    lines.push(`| Language | Bytes | Percentage |`);
    lines.push(`| :--- | :--- | :--- |`);
    for (const [lang, bytes] of languageEntries) {
      const percentage = totalBytes > 0 ? ((bytes / totalBytes) * 100).toFixed(1) : "0.0";
      lines.push(`| **${lang}** | ${bytes.toLocaleString()} B | ${percentage}% |`);
    }
  } else {
    lines.push(`*No language breakdown available.*`);
  }
  lines.push("");

  // 5. Contributors
  lines.push(`## 👥 Top Contributors`);
  if (contributors.length > 0) {
    lines.push(`| Contributor | Contributions | Profile |`);
    lines.push(`| :--- | :--- | :--- |`);
    contributors.slice(0, 10).forEach((c) => {
      lines.push(`| **${c.login}** | ${c.contributions.toLocaleString()} commits | [GitHub Profile](${c.html_url}) |`);
    });
    if (contributors.length > 10) {
      lines.push(`\n*And ${contributors.length - 10} more contributors.*`);
    }
  } else {
    lines.push(`*No contributor information available.*`);
  }
  lines.push("");

  // 6. AI Summary Section
  lines.push(`## 🤖 AI Summary`);
  if (aiSummary) {
    lines.push(aiSummary.trim());
  } else if (aiLoading) {
    lines.push(`*AI Summary is currently generating...*`);
  } else {
    lines.push(`*AI Overview has not been generated.*`);
  }
  lines.push("");

  // 7. AI Code Health Section
  lines.push(`## 🩺 AI Code Health Analysis`);
  if (codeHealth) {
    lines.push(`- **Overall Code Health Score:** **${codeHealth.overallScore} / 100**\n`);

    // Categories
    if (codeHealth.categories) {
      lines.push(`### Category Breakdown`);
      lines.push(`| Category | Score | Summary |`);
      lines.push(`| :--- | :--- | :--- |`);

      const categoryLabels: Record<keyof CodeHealthResult["categories"], string> = {
        architecture: "Architecture",
        maintainability: "Maintainability",
        codeQuality: "Code Quality",
        testing: "Testing",
        security: "Security",
        typeSafety: "Type Safety",
        documentation: "Documentation",
      };

      (Object.keys(codeHealth.categories) as Array<keyof CodeHealthResult["categories"]>).forEach((key) => {
        const cat = codeHealth.categories[key];
        if (cat) {
          lines.push(`| **${categoryLabels[key] || key}** | ${cat.score}/100 | ${cat.summary} |`);
        }
      });
      lines.push("");
    }

    // Strengths
    if (codeHealth.strengths && codeHealth.strengths.length > 0) {
      lines.push(`### Key Strengths`);
      codeHealth.strengths.forEach((strength) => {
        lines.push(`- ✅ ${strength}`);
      });
      lines.push("");
    }

    // Issues
    if (codeHealth.issues && codeHealth.issues.length > 0) {
      lines.push(`### Identified Issues`);
      codeHealth.issues.forEach((issue) => {
        const severityBadge = issue.severity.toUpperCase();
        lines.push(`- **[${severityBadge}] ${issue.title}**: ${issue.description}`);
        if (issue.files && issue.files.length > 0) {
          lines.push(`  - *Affected files:* ${issue.files.map((f) => `\`${f}\``).join(", ")}`);
        }
      });
      lines.push("");
    }

    // Recommendations
    if (codeHealth.recommendations && codeHealth.recommendations.length > 0) {
      lines.push(`### Recommendations`);
      codeHealth.recommendations.forEach((rec) => {
        const priorityBadge = rec.priority.toUpperCase();
        lines.push(`- **[${priorityBadge} PRIORITY] ${rec.title}**: ${rec.description}`);
      });
      lines.push("");
    }
  } else if (codeHealthLoading) {
    lines.push(`*AI Code Health analysis is currently processing...*`);
  } else if (codeHealthError) {
    lines.push(`*AI Code Health analysis is unavailable: ${codeHealthError}*`);
  } else {
    lines.push(`*AI Code Health analysis is unavailable or not generated.*`);
  }

  lines.push("\n---\n*Report exported from CodeOrbit GitHub-Analyzer*");

  return lines.join("\n");
}
